### ISSUE TITLE
Heap overwrite due to type confusion

### ISSUE THREAD

**Issue by tpericin** [microsoft/ProcMon-for-Linux#12]
There's a type mismatch here. On x64 platforms, where pointer size is greater than unsigned long, this will cause additional 4 bytes to be written after val on heap.

https://github.com/microsoft/ProcMon-for-Linux/blob/57eca030ef4f397680f0af9a61febaa21f0bc962/src/display/screen.cpp#L1128

This should instead be:

`int size = sizeof(unsigned long); `

Best regards,

**Comment by johan-boule** [comment]
Your fix is right. I just want to point out that only Microsoft Windows is using the LLP64 model, where "long" is still 32 bits, and you need "long long" to have 64 bits. All other platforms including Linux use at least LP64 (i.e. "long" is 64 bits).

**Comment by tpericin** [comment]
You're right, it is implementation defined. I was thinking about the worst case scenario here. Thanks for looking into it.

**Comment by josalem** [comment]
Good catch!  @jahabibi, can you make a PR for this?
