### ISSUE TITLE
Host it on the Microsoft packages repository

### ISSUE THREAD

**Issue by vanillajonathan** [microsoft/ProcMon-for-Linux#14]
Put packages somewhere on http://packages.microsoft.com/repos/

**Comment by jahabibi** [comment]
Hey @vanillajonathan the preview package is currently published to Microsoft's Ubuntu 18.04 package repository. You can find the [installation instructions here](https://github.com/microsoft/ProcMon-for-Linux/blob/main/INSTALL.md).

**Comment by vanillajonathan** [comment]
Hey @jahabibi, that's an old release. Is it only available on 18.04?
The new LTS release is version 20.04.

**Comment by jahabibi** [comment]
We are aware of the newer Ubuntu 20.04 LTS release and we will be supporting it as we move forward. For the initial release of Procmon Preview we are limited to Ubuntu 18.04 as BCC v0.10.0 does not support the newer kernel Ubuntu 20.04 ships with by default. Please follow #2 for updates as we address this to support newer kernels.
