### ISSUE TITLE
Install document does not explicitly have  cmake as a dependency

### ISSUE THREAD

**Issue by jouellnyc** [microsoft/ProcMon-for-Linux#19]
On the main page : 

https://github.com/microsoft/ProcMon-for-Linux/

sudo apt-get -y install bison build-essential flex git libedit-dev \
  libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev

could also reference 'cmake'

**Comment by jahabibi** [comment]
Hey @jouellnyc this is due to the fact that the default `cmake` package that ships with Ubuntu 18.04 LTS is less than the required `cmake v3.14`. This is why it is documented in the requirements as it allows people to install `cmake v3.14+` using their desired method.

**Comment by jouellnyc** [comment]
Howdy @jahabibi 

OK Very good! Thanks for the update.
