### ISSUE TITLE
Maybe required cmake should be >= 3.14

### ISSUE THREAD

**Issue by TETRA2000** [microsoft/ProcMon-for-Linux#22]
I found that `FetchContent_MakeAvailable` isn't available on cmake 3.13.0 when I tried to make this project.

```
..
-- Latest recognized Git tag is -128-NOTFOUND
-- Git HEAD is ad86920331dda3315538ab0ee30fb24727aff82d
-- Revision is 128-NOTFOUND-ad869203
-- Found LLVM: /usr/lib/llvm-6.0/include 6.0.0
-- Using static-libstdc++
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.a;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so  
CMake Error at CMakeLists.txt:49 (FetchContent_MakeAvailable):
  Unknown CMake command "FetchContent_MakeAvailable".


-- Configuring incomplete, errors occurred!
See also "/home/parallels/Procmon-for-Linux/build/CMakeFiles/CMakeOutput.log".
```

That command was introduced on cmake 3.14 according to its release note.
https://cmake.org/cmake/help/v3.14/release/3.14.html#modules

**Comment by rwperrott** [comment]
I had to download
     https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0-Linux-x86_64.sh
and
     sudo sh cmake-3.18.0-Linux-x86_64.sh  --skip-license --exclude-subdir --prefix=/usr/local
to get a past 3.14.* recent version on Mate LMDE4, then it built fine.
