### ISSUE TITLE
procMon for macOS.

### ISSUE THREAD

**Issue by iradization** [microsoft/ProcMon-for-Linux#37]
Hi, just interested to know if there are any plans to port this project to macOS as well? 
I know from experience the apple doesn't willing to provide descent unified API to acquire all process contents (no /proc library), and wrapping it with such tool would be greatly welcomed.

**Comment by damolp** [comment]
Did you look at the code?

It uses eBPF under the hood, so you're out of luck for MacOS support. Closest thing you'll get on MacOS is dtrace. 

@brendangregg might be able to work some magic however

**Comment by jahabibi** [comment]
Unfortunately at this point in time we do not have macOS on our roadmap for future support.
