### ISSUE TITLE
Sudo required

### ISSUE THREAD

**Issue by oneEdoubleD** [microsoft/ProcMon-for-Linux#5]
Would it be possible to use ProcMon, even if just a limited subset of features, without requiring sudo?

**Comment by MarioHewardt** [comment]
At this time, sudo is required for most all of procmon functionality.

**Comment by oneEdoubleD** [comment]
Ah that's a shame, dtrace can work for all non-escalated processes so I thought it might be possible. Looks good anyway, thanks for porting to Linux :)
